import Head from "next/head";
import styles from "../styles/Home.module.css";

import {
  auth,
  logout,
  addMessage,
  getUsers,
  addUser,
} from "../Firebase/FirebaseConfig";

// react-firebase-hooks reduced boiler plate and mmade firebase interactions much more easier, use more often
import { useAuthState } from "react-firebase-hooks/auth";

import { GoogleSignIn } from "../components/GoogleSignIn";
import { SignInWithEmailAndPassword } from "../components/SignInWithEmailAndPassword";
import { ChatRoom } from "../components/ChatRoom";

export default function Home() {
  // Firebase Hook to listen to change in user authentication
  const [user, loading, error] = useAuthState(auth);

  const SignOut = () => {
    return <button onClick={() => logout(auth)}>Sign Out</button>;
  };

  return (
    <div>
      <Head>
        <title>Chat App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <section>
          {user ? (
            "User Signed In"
          ) : (
            <>
              <SignInWithEmailAndPassword auth={auth} />
              <GoogleSignIn auth={auth} />
            </>
          )}
        </section>
        <section>{user ? <SignOut /> : "User is not signed in"}</section>
        <button onClick={getUsers}>Get Users (Console Log)</button>
        <button onClick={addUser}>Add User (Hardcoded)</button>
        <button onClick={addMessage}>Add Message (Hard coded user)</button>

        <ChatRoom />
      </main>
    </div>
  );
}
